package ru.mephi.mortalkombatbLab5;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import ru.mephi.mortalkombatbLab5.enums.PlayerChosenBoost;

import javax.swing.*;
import java.awt.*;
import java.awt.event.KeyEvent;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.Random;

public class ChooseLevelUpBoost extends JDialog {
    private JPanel contentPane;
    private JButton buttonHealth;
    private JButton buttonDamage;
    private JButton buttonRandom;
    private final PlayerChosenBoostWrapper boostWrapper;

    public ChooseLevelUpBoost(PlayerChosenBoostWrapper boostWrapper) {
        this.boostWrapper = boostWrapper;
        setContentPane(contentPane);
        setModal(true);
        getRootPane().setDefaultButton(buttonHealth);

        buttonHealth.addActionListener(e -> chooseHealth());

        buttonDamage.addActionListener(e -> chooseDamage());

        buttonRandom.addActionListener(e -> random());

        // call onCancel() when cross is clicked
        setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        addWindowListener(new WindowAdapter() {
            public void windowClosing(WindowEvent e) {
                random();
            }
        });

        // call onCancel() on ESCAPE
        contentPane.registerKeyboardAction(e -> random(),
                KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0),
                JComponent.WHEN_ANCESTOR_OF_FOCUSED_COMPONENT);
    }

    private void chooseHealth() {
        this.boostWrapper.setPlayerChosenBoost(PlayerChosenBoost.HEALTH);
        dispose();
    }

    private void chooseDamage() {
        this.boostWrapper.setPlayerChosenBoost(PlayerChosenBoost.DAMAGE);
        dispose();
    }

    private void random() {
        int randInt = new Random().nextInt(0, 2);
        switch (randInt) {
            case 0 -> chooseDamage();
            case 1 -> chooseHealth();
        }
    }


    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        contentPane = new JPanel();
        contentPane.setLayout(new GridLayoutManager(1, 1, new Insets(10, 10, 10, 10), -1, -1));
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new GridLayoutManager(2, 1, new Insets(0, 0, 0, 0), -1, -1));
        contentPane.add(panel1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, 1, null, null, null, 0, false));
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new GridLayoutManager(1, 2, new Insets(0, 0, 0, 0), -1, -1, true, false));
        panel1.add(panel2, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        buttonHealth = new JButton();
        buttonHealth.setActionCommand("chooseHealth");
        buttonHealth.setLabel("Здоровье");
        buttonHealth.setText("Здоровье");
        panel2.add(buttonHealth, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        buttonDamage = new JButton();
        buttonDamage.setActionCommand("chooseDamage");
        buttonDamage.setLabel("Урон");
        buttonDamage.setText("Урон");
        panel2.add(buttonDamage, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        buttonRandom = new JButton();
        buttonRandom.setActionCommand("random");
        buttonRandom.setText("Выбрать случайно");
        panel1.add(buttonRandom, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return contentPane;
    }

}
